modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
    modId = "svruptime"
    version = "${version}"
    displayName = "svrUptime"
    description = "Broadcasts server uptime in Minecraft and real-world time at the start of each in-game day."

[[dependencies.svruptime]]
    modId = "neoforge"
    type = "required"
    versionRange = "[26.1,26.2)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.svruptime]]
    modId = "minecraft"
    type = "required"
    versionRange = "[26.1,26.2)"
    ordering = "NONE"
    side = "BOTH"
