modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
    modId = "svruptime"
    version = "${version}"
    displayName = "svrUptime"
    description = "Broadcasts server uptime in Minecraft and real-world time at the start of each in-game day."

[[dependencies.svruptime]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.11,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.svruptime]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.svruptime]]
    modId = "architectury"
    type = "required"
    versionRange = "*"
    ordering = "NONE"
    side = "BOTH"
